version: '1.0'

services:
  regretion-test: # random name
#    image: maven:3.9.6-sapmachine-21 # target image from hub.docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "mvn clean test"
    working_dir: /usr/workspace
